name: ci-develop
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: godot-gdunit-labs/gdUnit4-action@v1
        with:
          godot-version: '4.6.1'
          paths: 'res://tests'
          timeout: 10
          version: 'installed'
          publish-report: false
          report-name: 'log4godot-test-report.xml'
